--- 
title: "Outstanding User Interfaces with Shiny Book Club"
author: "The Data Science Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-shinyui
description: "This is the product of the Data Science Learning Community's Outstanding User Interfaces with Shiny Book Club."
---

# Welcome {-}

Welcome to the bookclub! 

This is a companion for the book [_Outstanding User Interfaces with Shiny_](https://unleash-shiny.rinterface.com/index.html) by David Granjon (Chapman & Hall, copyright August 31, 2022, [9780367645267](https://www.routledge.com/Outstanding-User-Interfaces-with-Shiny/Granjon/p/book/9780367645267)).
This companion is available at [dslc.io/shinyui](https://dslc.io/shinyui).

This website is being developed by the [Data Science Learning Community](https://dslc.io). Follow along, and [join the community](https://dslc.io/join) to participate.

This companion follows the [Data Science Learning Community Code of Conduct](https://dslc.io/conduct).

## Book club meetings {-}

- Each week, a volunteer will present a chapter from the book (or part of a chapter).
  - **This is the best way to learn the material.**
- Presentations will usually consist of a review of the material, a discussion, and/or a demonstration of the principles presented in that chapter.
- More information about how to present is available in the [github repo](https://github.com/r4ds/bookclub-shinyui).
- Presentations will be recorded, and will be available on the [Data Science Learning Community YouTube Channel](https://dslc.io/youtube).

## Pace {-}

- We'll _try_ to cover 1 chapter/week, but...
- ...It's ok to split chapters when they feel like too much.
- We will try to meet every week, but will likely take some breaks for holidays, etc.
